"""empty message

Revision ID: 215afd1ccdf8
Revises: 29c9de8a48ab
Create Date: 2020-04-13 01:41:56.552084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215afd1ccdf8'
down_revision = '29c9de8a48ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(precision=5), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###
