"""empty message

Revision ID: 290a15fe89a6
Revises: 5ec2b89be8ad
Create Date: 2020-04-11 21:31:39.971022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290a15fe89a6'
down_revision = '5ec2b89be8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('jokes', sa.Column('maturity', sa.Integer(), nullable=True))
    op.add_column('jokes', sa.Column('score', sa.Numeric(precision=5), nullable=True))
    op.add_column('jokes', sa.Column('text', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'jokes', ['text'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jokes', type_='unique')
    op.drop_column('jokes', 'text')
    op.drop_column('jokes', 'score')
    op.drop_column('jokes', 'maturity')
    op.drop_column('jokes', 'categories')
    # ### end Alembic commands ###
