"""empty message

Revision ID: 3c2b3ef8f533
Revises: 7212fdd258fa
Create Date: 2020-04-11 16:53:05.528111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2b3ef8f533'
down_revision = '7212fdd258fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('score', sa.Numeric(precision=5), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###
