"""empty message

Revision ID: 5ec2b89be8ad
Revises: f01c4d999074
Create Date: 2020-04-11 21:31:10.840731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ec2b89be8ad'
down_revision = 'f01c4d999074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jokes_text_key', 'jokes', type_='unique')
    op.drop_column('jokes', 'maturity')
    op.drop_column('jokes', 'score')
    op.drop_column('jokes', 'categories')
    op.drop_column('jokes', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('text', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('jokes', sa.Column('categories', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('jokes', sa.Column('score', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True))
    op.add_column('jokes', sa.Column('maturity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('jokes_text_key', 'jokes', ['text'])
    # ### end Alembic commands ###
