"""empty message

Revision ID: 6e4d7cad0177
Revises: 3c2b3ef8f533
Create Date: 2020-04-11 21:29:43.485895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e4d7cad0177'
down_revision = '3c2b3ef8f533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('categories', postgresql.ARRAY(sa.VARCHAR(length=128)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
