"""empty message

Revision ID: 6e8d36765593
Revises: 20c5cfdc4de8
Create Date: 2020-04-11 21:54:07.761400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8d36765593'
down_revision = '20c5cfdc4de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(precision=5), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###
