"""empty message

Revision ID: d53f0e239162
Revises: 9d2e388c1340
Create Date: 2020-04-13 01:13:36.282492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd53f0e239162'
down_revision = '9d2e388c1340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.VARCHAR(length=128)), autoincrement=False, nullable=True),
    sa.Column('score', sa.NUMERIC(precision=5, scale=0), autoincrement=False, nullable=True),
    sa.Column('maturity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jokes_pkey'),
    sa.UniqueConstraint('text', name='jokes_text_key')
    )
    # ### end Alembic commands ###
