"""empty message

Revision ID: ed2770f9cc9f
Revises: 92f33ba51968
Create Date: 2020-04-13 01:39:29.621339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2770f9cc9f'
down_revision = '92f33ba51968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(precision=5), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jokes')
    # ### end Alembic commands ###
