"""empty message

Revision ID: f01c4d999074
Revises: 6e4d7cad0177
Create Date: 2020-04-11 21:30:37.294560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01c4d999074'
down_revision = '6e4d7cad0177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('categories', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jokes', 'categories')
    # ### end Alembic commands ###
