flask:
    image: <YOUR DOCKER USERNAME>/flask-template:v1
    ports:
      - "5000:5000"
    environment:
    - APP_SETTINGS=config.ProductionConfig
    - DATABASE_URL=postgresql://localhost/my_app_db
