apiVersion: apps/v2
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: navinr13/flask-template:v2
          env:
            - name: APP_SETTINGS
              value: config.DevelopmentConfig
            - name: DATABASE_URL
              value: postgresql://localhost/my_app_db
          ports:
            - containerPort: 5000
